apiVersion: v1
kind: Service
metadata:
  name: backend-common-mocker-v2
  namespace: mockers
  labels:
    app: backend-common-mocker-v2
    version: v2
spec:
  ports:
    - port: 3000
      name: http-listen
  selector:
    app: backend-common-mocker-v2
    version: v2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-common-mocker-v2
  namespace: mockers
  labels:
    app: backend-common-mocker-v2
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-common-mocker-v2
      version: v2
  template:
    metadata:
      namespace: mockers
      labels:
        app: backend-common-mocker-v2
        version: v2
    spec:
      containers:
        - name: backend-common-mocker-v2
          image: mxudong/trace-mocker:v1.0.3
          ports:
            - containerPort: 3000
              name: http-server
          env:
            - name: NODE_ID
              value: backend-common-mocker-v2