apiVersion: v1
kind: Service
metadata:
  name: user-mocker
  namespace: mockers
  labels:
    app: user-mocker
    version: v1.0.3
spec:
  ports:
    - port: 3000
      name: http-listen
  selector:
    app: user-mocker
    version: v1.0.3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-mocker
  namespace: mockers
  labels:
    app: user-mocker
    version: v1.0.3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-mocker
      version: v1.0.3
  template:
    metadata:
      namespace: mockers
      labels:
        app: user-mocker
        version: v1.0.3
    spec:
      containers:
        - name: user-mocker
          image: mxudong/trace-mocker:v1.0.3
          ports:
            - containerPort: 3000
              name: http-server
          env:
            - name: NODE_ID
              value: user-mocker